import { build } from "esbuild";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const modules = resolve(here, "node_modules");
const vendor = resolve(here, "../../web/vendor");
const empty = resolve(here, "empty.cjs");

await rm(vendor, { recursive: true, force: true });
await mkdir(vendor, { recursive: true });

// netmd-js and himd-js are CommonJS packages written for Node.js; bundle them with browser shims.
await build({
  entryPoints: [resolve(here, "entry.js")],
  outfile: resolve(vendor, "md-lib.js"),
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2020",
  minify: true,
  legalComments: "eof",
  inject: [resolve(here, "shims.js")],
  alias: {
    usb: empty,
    worker_threads: empty,
    fs: empty,
    path: empty,
    zlib: empty,
    util: resolve(here, "util-shim.cjs"),
    stream: "stream-browserify",
  },
  logLevel: "warning",
});

// Node.js bundle of himd-js for the local server's Hi-MD USB mode. Only pure-JS dependencies are
// bundled; the native "usb" package is loaded separately by native/himd-usb.mjs.
const nativeVendor = resolve(here, "../../native/vendor");
await rm(nativeVendor, { recursive: true, force: true });
await build({
  entryPoints: [resolve(here, "native-entry.js")],
  outfile: resolve(nativeVendor, "himd-node.cjs"),
  bundle: true,
  format: "cjs",
  platform: "node",
  target: "node20",
  minify: true,
  legalComments: "eof",
  external: ["usb"],
  logLevel: "warning",
});

// @ffmpeg/ffmpeg starts its worker from "./worker.js" relative to itself, so it must be served from this origin.
const ffmpegRoot = resolve(modules, "@ffmpeg/ffmpeg/dist/esm");
await cp(ffmpegRoot, resolve(vendor, "ffmpeg"), {
  recursive: true,
  filter: (source) => !source.endsWith(".d.ts") && !source.endsWith(".d.mts"),
});

const versions = {};
for (const name of ["netmd-js", "himd-js", "@ffmpeg/ffmpeg"]) {
  versions[name] = JSON.parse(await readFile(resolve(modules, name, "package.json"), "utf8")).version;
}
await writeFile(resolve(vendor, "README.md"), `# Vendored MiniDisc libraries

Generated by \`npm run build:md-lib\`. Do not edit by hand.

| File | Source | Version | License |
| --- | --- | --- | --- |
| md-lib.js | [netmd-js](https://github.com/cybercase/netmd-js), [himd-js](https://github.com/asivery/himd-js) and their dependencies | ${versions["netmd-js"]}, ${versions["himd-js"]} | GPL-2.0 (see legal comments at the end of the file) |
| ../../native/vendor/himd-node.cjs | himd-js for Node.js (Hi-MD direct USB on the local server) | ${versions["himd-js"]} | GPL-2.0 |
| ffmpeg/ | [@ffmpeg/ffmpeg](https://github.com/ffmpegwasm/ffmpeg.wasm) | ${versions["@ffmpeg/ffmpeg"]} | MIT |

The ffmpeg.wasm core (GPL-2.0-or-later) is downloaded by the browser from jsDelivr at runtime.
`, "utf8");
process.stdout.write(`Built ${vendor}\n`);
